import React from 'react';

export default function Marquee() {
  return (
    <div className="marquee">
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/hat_1hat.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/armor_1armor.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/crown_1crown.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/hat_1hat.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/armor_1armor.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/crown_1crown.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/hat_1hat.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/armor_1armor.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/crown_1crown.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/hat_1hat.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/armor_1armor.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/crown_1crown.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/hat_1hat.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/armor_1armor.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/crown_1crown.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/hat_1hat.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/armor_1armor.png"
        alt=""
        className="slider-image"
      />
      <img
        src="https://storage.googleapis.com/geometric-watch-246204.appspot.com/images/crown_1crown.png"
        alt=""
        className="slider-image"
      />
    </div>
  );
}
