export const HERO_CHARACTER = [
  'Gender',
  'Body',
  'Eye',
  'Mouth',
  'Ear',
  'Tail',
  'Pattern',
  'Wild1',
  'Wild2',
  'Primary Color',
  'Accent Color',
  'Pattern Color',
  'HairColor',
  'Eye Color',
];

export const HERO_TRAITS_CODE = [
  ['M', 'F'],
  ['G', 'H', 'Z', 'X', '2', '4'],
  ['A', 'B', 'D', 'F', 'H', 'K', '2', '4', '6'],
  ['I', 'P', 'E', 'W', 'D', 'S', '5', '7', '9'],
  ['Y', 'K', 'L', 'R', '9', '4'],
  ['J', 'V', 'X', 'O', '2', '5'],
  ['Q', 'R', 'W', 'E', '4', '2'],
  ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
  ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
  ['Y', 'O', 'G', 'B', 'W', 'L', 'H', 'J', 'r', 'p', 'b', 'm'],
  ['Y', 'O', 'G', 'B', 'W', 'L', 'r', 'p', 'b'],
  ['Y', 'O', 'G', 'B', 'T', 'L', 'H', 'M', 'r', 'p', 'b', 'j'],
  ['Y', 'O', 'G', 'B', 'W', 'L', 'r', 'p', 'b'],
  ['Y', 'O', 'G', 'B', 'T', 'L', 'H', 'M', 'r', 'p', 'b', 'j'],
];

export const HERO_TRAITS_NAME = [
  ['Male', 'Female'],
  ['Calzone', 'Hot Wing', 'Mama Mia', 'Breadstick', 'Dough Boy', 'Bagel Bite'],
  [
    'Margarita',
    'Meatballs',
    'Cutie Pie',
    'Crusty',
    'Salty',
    'Olives',
    'Icey',
    'Soggy',
    'Undercooked',
  ],
  [
    'Sweet Tea',
    'Chompy',
    'Stale',
    'Saucy',
    'Cheeser',
    'Cutie Pie',
    'Garlic',
    'Stalemate',
    'Rustic',
  ],
  ['Soggy', 'Fluffy', 'Deep Dish', 'Nibble', 'Shroomie', 'Mystic'],
  [
    'Thin Crust',
    'Deep Dish',
    'Stinky Cheese',
    'Readymade',
    'Porkypie',
    'Mushroom',
  ],
  ['Gumdrop', 'Moomoo', 'Boxer', 'Splatter', 'Time Traveler', 'Rawwr'],
  [],
  [],
  [
    'Lemonade',
    'Orange Soda',
    'Cloudy',
    'Midnight',
    'Milk Shake',
    'Blue Rasberry',
    'Rocket',
    'Seahorse',
    'Grape Soda',
    'Rosie',
    'Stone Oven',
    'Leafy',
  ],
  [
    'Moonchild',
    'Strawberry Milk',
    'Macaron',
    'Vanilla',
    'Slime',
    'Earl Grey',
    'Sky',
    'Gummy',
    'Lemon Head',
  ],
  [
    'Sour Apple',
    'Cherry Tart',
    'Banana Pudding',
    'Blue Hawaiian',
    'Bubble Gum',
    'Jelly Bean',
    'Orange Cream',
    'Chocolate Brownie',
    'Rock Candy',
    'Blueberry Pie',
    'Cotton Candy',
    'Black Licorice',
  ],
  [
    'Jet',
    'Firebird',
    'Brown Sugar',
    'Cinnamon Spice',
    'Horchata',
    'Peanut Butter',
    'Pony',
    'Boquest',
    'Rasberry Jelly',
  ],
  [
    'Sour Apple',
    'Cherry Tart',
    'Banana Pudding',
    'Blue Hawaiian',
    'Bubble Gum',
    'Jelly Bean',
    'Orange Cream',
    'Chocolate Brownie',
    'Rock Candy',
    'Blueberry Pie',
    'Cotton Candy',
    'Black Licorice',
  ],
];
